travis:
  secure:
    BINSTAR_TOKEN: O/CSmrCg4NFTOUgIa+II3LTNzngpmpLZIKYIneJoVZDT/jdCTWCTRzeECN9wIRHtW6l2mdSyw+65Tx24Zbo6KCeqoQ1ZfFRRUl0yP5hS9OYsiPzU629zS9/6axUMG6aVztWZ+XML2TeEqcitpacaP3ouDoyNlg3x1fVb/M0q+tHsNnKQWMfLnjiFU18Dg0/ZKLrj8xHaJ1RKu8zuG2O6wTtXJb3qc27hMd/NNfkrne7hlamuP7rHTTDEAoR+hmmYy6YeJps34Hni88rQ02Bdk7U3dw3ig5VxlkdaladU0qfPg6zXXvmr5CMIlAR4g84zFnih3fwcq1m6UfG4YRCMJdLG+5eLSK4fV1vhYl0TE0nwNn8T1adcx8JCfjF3DrqXr3HUNw3MJbuPfA43MU5PqDDEulk9LHB+YMY25UoYLLMX9+lfym5WIQ2eb9h9mxVhLHTD+LYbk4nMYWkmJ1U5J9vwCn8NNWQRT8uZl5Oj+0hWLCgy5WMy6vTSthNfwKTdajVATSgVlqeVezZabBXnYJKP5K2R/SDgskc7Zf9tfvmzgLSaPBp5KMrW1Y0yygcpgC1l4asrQB/Z0mXUxB+AIppKtLv6UB76P2LGkxYO3ZyIjkp0rb5yPIhQqJCdLrA5ltkJMmMC16pCrLe1w2QPXBW0oEosSJaFBgsnBkaxiVE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
