travis:
  secure:
    BINSTAR_TOKEN: n7ZKns4UkPvV7tJ5mX1vmpCOa99qFfkbCXuW6CukVZqXwF4QVQYhVCXWND1mLSBXftWGI677FTgyBm5DRLyY1pWrIB9PoraeDWLziUqM/Mv/MRyIH8oSMZp5mPnL4TTuMlKNRM5K0y1eYULuBiABrSABlOkF98ntpFuR2d3oPFKQMCy+KeyOYniS8yUPYAVs6YzXttiU7nMI9UkzG45NLii+oUVEiXkMmEdbIJSLlgcRewQTOeshygk6SWj70fNqnQjPfpCjhJy1GGHmaros7IT0D3w2gtt+2L5zrMBhIY2URn3888OrvwNS7datGFIXkTptNH6wKgaF+Miq5wHBsO4f4c3Ct6r+jm/cwPpUPD5X6uWC17somJ+WW/dGWckeBTYMP9mOs2pHzPDItfFEsk+lrrprvZunq6QwJvEPgDQxydHyBV+7fuicyDJo7a66LebkTBjUnr4SjEe6N26U62DFs6N0+aYmK0KZrusFjR5/Drq5gxV5s8u8+IJV53rVlunDnG60EKzSJKPIz7kuHxSWbuoHu7xTkgRk+bxXtnvR0yexyjfiKAVvHcA05QsuGP+pGSvVW1zKZB3b/8yXkI6T/MVRv9W6Xzzi2oy0gB2+YIirHwA08WYun0o3QfMHByYDHa4Y9agJ2tA2w0h277QhXrVwbOD4mJ2Mbz4AKJo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
