travis:
  secure:
    BINSTAR_TOKEN: NXR3Z1cEGofVbvH6oethHgSLm0Mf4GnZNh3iNT4xwtpmJVBGMqtvx5TPB3kbAUoWLud8o/NaYMx0DiZrypXBLwKxZRM70IsFISK8WY5Zc43VDOKnHsZiQ2Ba2vs8ieEBfNGtpG2lK2wTGIHf47JIqJHX5g5TWGrF65h1gvbhIOkxitlmGXj90uAlipj3kwX1d0OPtB//em0oh74mMeq6OB/nt2VdnpFT7wVaQNFhj6sGdju6BJlowgF2qurfXtiz3BIflmF6jbWWQTzLZmM548zenUud6/P1zFNpOAzrm3JxeTRhKM1cuegWVBgIjm8m9gPMa+VZ62HkEK/NUgkK39JHIT3S4/ikLQHx2NXLOTRJF+fFw2tIzOy2U4R7vWsaUFquwRKlM9x2WaRI6gCwQHCYAzYiTY4s6M12Kqcc8QnVNx/cN2vtP7qtqx6shdlLMe63iBLuZMo0TKj6p52MJtn3A5gCBLGa4D18dfMigQVGDsPbMoiIGWJxxBVmM1dbHHMcT8lha+FC+i0yU4nkYoTbzdTMGkXspc65zJY2RlOLPedtSEDFFx9JOCBRgLVX0g0kVfROvzpwj+aVwrMx2Zh60hPbYhH+bBaFa/wW1Xg8mmOvhJMP9PKlHzzMb4s7qW7rQCzc1HjLCvvAuzHkJexOQ6ArRI1+JaeE00BC1yw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
